# Generated by Django 4.2.8 on 2024-01-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2000-7-22'),
            preserve_default=False,
        ),
    ]
